name: nomorepass
version: 1.0.0
homepage: https://nomorepass.com
description: >-
  LibrerÃ­as para el uso de nomorepass
  desde Flutter
environment:
  sdk: '>=2.13.0 <3.0.0'
dependencies: 
  encrypt: ^5.0.0
  http: ^0.13.3
  crypto: ^3.0.1
